name: "publish"

on:
  workflow_dispatch:
  push:
    tags:
      - '[0-9]+\.[0-9]+\.[0-9]+'
      - '[0-9]+\.[0-9]+\.[0-9]+\-rc\[0-9]+'

jobs:
  publish-tauri:
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest" # for Arm based macs (M1 and above).
            args: "--target aarch64-apple-darwin"
            target: aarch64-apple-darwin
            runner: macos-latest
          
          - platform: "macos-latest" # for Intel based macs.
            args: "--target x86_64-apple-darwin"
            target: x86_64-apple-darwin
            runner: macos-latest
          
          - platform: "ubuntu-22.04" # for Linux
            args: ""
            target: x86_64-unknown-linux-gnu
            runner: ubuntu-latest
          
          - platform: "windows-latest" # for Windows
            runner: windows-latest
            args: ""
            target: x86_64-pc-windows-msvc

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04' # This must match the platform value defined above.
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable # Set this to dtolnay/rust-toolchain@nightly
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Add Rust Target
        run: rustup target add ${{ matrix.target }}

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: "v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: false
          prerelease: false


      - name: Build Portable Binaries (Windows)
        if: ${{ matrix.runner == 'windows-latest' }}
        run: |
          cargo build --target ${{ matrix.target }}
          cargo build --release --target ${{ matrix.target }}
          mv ./target/${{ matrix.target }}/debug/longchamp-budget.exe ./target/${{ matrix.target }}/debug/longchamp-budget_${{ github.ref_name }}_x64-portable.exe
          mv ./target/${{ matrix.target }}/release/longchamp-budget.exe ./target/${{ matrix.target }}/release/longchamp-budget_${{ github.ref_name }}_x64-portable.exe

      - name: Upload Portable Binaries (Windows)
        if: ${{ matrix.runner == 'windows-latest' }}
        run: bash -c 'gh release upload ${{ github.ref_name }} ./target/${{ matrix.target }}/{debug/longchamp-budget_${{ github.ref_name }}_x64-portable.exe,release/longchamp-budget_${{ github.ref_name }}_x64-portable.exe} --clobber'